### ISSUE TITLE
How to start task with host ip automatically after host __E_NAME__

### ISSUE THREAD

**Issue by dv4mp1r3** [gwen001/actarus#2]
I saw this feature in demo VM but I can't repeat it in anywhere.
Host task doesn't have any callbacks in both cases, but nmap is called every time when new server was detected.
I can implement it in "create" method of actarus/src/ArusServerBundle/Controller/ServiceController.php class (like other "custom" logic), but I think it's not good way to solve problem.

**Comment by gwen001** [comment]
Hum yes I didn't find a good way to implement complex callback so I put the code in the interpreter module:
`actarus/src/AppBundle/Command/InterpretTaskCommand.php`

**Comment by dv4mp1r3** [comment]
Got it, thanks for answer!
to other users: you need to implement method named like your task in InterpretTaskCommand class
@gwen001 may be better way is create namespace and split on classes for task post processing? Oh, and can you follow me on [twitter](https://twitter.com/dv4mp1r3)? I have few more questions about project architecture and contributing :)

**Comment by gwen001** [comment]
Yes you're right it would be better to have a dedicated class for each task, that's in the top 100 of my todo list :)
