### ISSUE TITLE
An error occured, feel free to contact us.

### ISSUE THREAD

**Issue by Neolex-Security** [gwen001/actarus#4]
Hello,
Thanks for this awesome project !
I'm trying to use it but in the dashboard I got : "An error occured, feel free to contact us." 
I would like to know if there is a way to  find which error is it ?
Thanks

Edit: I think i found (by going to app_dev.php ?) I got this error : Notice: Undefined offset: 0  in src/AppBundle/Controller/ServiceController.php at line 44  -

**Comment by gwen001** [comment]
Yes sorry , when performing your tests, you better use `app_dev.php` and keep PHP log opened on the side.

**Comment by Neolex-Security** [comment]
Do you know where this error come from ? I just want to use actarus I didnt try to make add myself.

**Comment by gwen001** [comment]
I have no idea, can be many things. Do you have anything in the PHP log ?

**Comment by Neolex-Security** [comment]
yes : "[Wed Feb 06 09:49:28.312078 2019] [:error] [pid 8683] [client 127.0.0.1:38942] PHP Notice:  Undefined offset: 0 in /var/www/html/actarus/src/AppBundle/Controller/ServiceController.php on line 44, referer: http://local.actarus.net/login"

**Comment by Neolex-Security** [comment]
Ok the problem was with my database, sorry for the inconvenience, thanks you !

Edit : That error happen when we delete the actarus project

**Comment by gwen001** [comment]
You should not delete that project. Never.
